feat: added scaledobject support for downscaler/downtime-replicas
caas-team/py-kube-downscaler pull request #100
Opened 2024-10-12 17:39 UTC by samuel-esp

## Motivation

Actually ScaledObject doesn't support "downscaler/downtime-replicas" annotation. See issue #96 

## Changes

- Refactored Keda ScaledObject resource class in order to support "downscaler/downtime-replicas" annotation
- Refactored scaler.py class in order to support "downscaler/downtime-replicas" annotation for Keda
- Added Unit Tests
- Refactored Docs

## Tests done

- Unit Tests

## TODO

- [x] I've assigned myself to this PR

2024-10-13 20:12 UTC, jonathan-mayer requested changes
Other than these two and me finding it a bit weird needing to specify the downtime replicas on the scaled objects deployments, ... this looks good to me

2024-10-13 20:12 UTC, jonathan-mayer commented on kube_downscaler/resources/keda.py
Maybe we should change this to -1 indicating the pause annotation not being set during downscaling. I think it would be more intuitive

2024-10-13 20:12 UTC, jonathan-mayer commented on kube_downscaler/scaler.py
> +# for Deployment/StatefulSet.spec.template.replicas. This value is usefult to allow
If we decide to keep this variable, the comment has to be changed
```suggestion
# for Deployment/StatefulSet.spec.template.replicas. This value is used to allow
```

2024-10-14 07:04 UTC, samuel-esp commented on kube_downscaler/resources/keda.py
Even better, you are right. I'm gonna change this today

2024-10-14 17:56 UTC, samuel-esp commented on kube_downscaler/resources/keda.py
@jonathan-mayer just checked against the original code, unfortunately `replicas=-1` couldn't be supported with the actual flow of the main algorithm

see this portion

```python
replicas = get_replicas(resource, original_replicas, uptime)
            update_needed = False

            if (
                not ignore
                and is_uptime
                and replicas == downtime_replicas
                and original_replicas
                and original_replicas > 0
            ):
                scale_up(
                    resource,
                    replicas,
                    original_replicas,
                    uptime,
                    downtime,
                    dry_run=dry_run,
                    enable_events=enable_events,
                )
                update_needed = True
            elif (
                not ignore
                and not is_uptime
                and replicas > 0
                and replicas > downtime_replicas
            ):
                if within_grace_period(
                    resource, grace_period, now, deployment_time_annotation
                ):
                    logger.info(
                        f"{resource.kind} {resource.namespace}/{resource.name} within grace period ({grace_period}s), not scaling down (yet)"
                    )
                else:
                    scale_down(
                        resource,
                        replicas,
                        downtime_replicas,
                        uptime,
                        downtime,
                        dry_run=dry_run,
                        enable_events=enable_events,
                    )
                    update_needed = True
```

basically inside the elif replicas=-1 > 0 will make skip the scale_down phase

2024-10-14 18:02 UTC, samuel-esp commented
> Other than these two and me finding it a bit weird needing to specify the downtime replicas on the scaled objects deployments, ... this looks good to me

I see this concern and I strongly agree with you on a theoretical level, ScaledObject is basically a custom HPA and doesn't hold the concept of "replicas". However since the ScaledObject controls the Deployment/StatefulSet through the pause annotation, it will invalid the `"downscaler/downtime-replicas"` if set at Deployment/StatefulSet level. It must be clear to the user, as stated on the documentation, that `"downscaler/downtime-replicas"` value should be the same inside both objects, otherwise it won't make sense

2024-10-15 05:59 UTC, jonathan-mayer commented
> > Other than these two and me finding it a bit weird needing to specify the downtime replicas on the scaled objects deployments, ... this looks good to me
> 
> I see this concern and I strongly agree with you on a theoretical level, ScaledObject is basically a custom HPA and doesn't hold the concept of "replicas". However since the ScaledObject controls the Deployment/StatefulSet through the pause annotation, it will invalid the `"downscaler/downtime-replicas"` if set at Deployment/StatefulSet level. It must be clear to the user, as stated inside the documentation, that `"downscaler/downtime-replicas"` value should be the same inside both objects, otherwise it won't make sense

I am not too familiar with ScaledObjects but I think it would make more sense if we "excluded" the Workloads that are being managed by the ScaledObject and let the ScaledObject scale them according to the pause annotation we set on it when scaling down.

2024-10-15 06:06 UTC, jonathan-mayer commented on kube_downscaler/resources/keda.py
maybe we could add an `or replicas == -1`. I don't think it would change anything within the scale down function

2024-10-15 07:33 UTC, samuel-esp commented on kube_downscaler/resources/keda.py
I'll try that in the afternoon, and I'll let you know

2024-10-15 18:39 UTC, samuel-esp commented on kube_downscaler/resources/keda.py
@jonathan-mayer made it work with `replicas=-1`. Thanks again for the suggestion, the code looks more clear now

2024-10-15 18:41 UTC, samuel-esp commented
> > > Other than these two and me finding it a bit weird needing to specify the downtime replicas on the scaled objects deployments, ... this looks good to me
> > 
> > 
> > I see this concern and I strongly agree with you on a theoretical level, ScaledObject is basically a custom HPA and doesn't hold the concept of "replicas". However since the ScaledObject controls the Deployment/StatefulSet through the pause annotation, it will invalid the `"downscaler/downtime-replicas"` if set at Deployment/StatefulSet level. It must be clear to the user, as stated inside the documentation, that `"downscaler/downtime-replicas"` value should be the same inside both objects, otherwise it won't make sense
> 
> I am not too familiar with ScaledObjects but I think it would make more sense if we "excluded" the Workloads that are being managed by the ScaledObject and let the ScaledObject scale them according to the pause annotation we set on it when scaling down.

That's a good approach as well, I included this piece of advice inside the usage notes of the docs in the ScaledObject section

2024-10-16 08:49 UTC, jonathan-mayer requested changes
If possible we should consider to automatically exclude the workloads managed by the ScaledObject.

2024-10-16 08:49 UTC, jonathan-mayer commented on kube_downscaler/scaler.py
> +                and (replicas > downtime_replicas or replicas == -1)
```suggestion
                and (replicas > 0 
                and replicas > downtime_replicas 
                or replicas == -1)
```

2024-10-16 09:02 UTC, samuel-esp commented
> If possible we should consider to automatically exclude the workloads managed by the ScaledObject.

I'll try to address this inside one of the next releases

2024-10-16 09:05 UTC, jonathan-mayer approved these changes

2024-10-16 10:04 UTC, merged