Fix: --pi-server-timeout Argument Doesn't Override Default Timeout Value
caas-team/py-kube-downscaler pull request #117
Opened 2024-11-20 18:37 UTC by samuel-esp

## Motivation

The newly introduced --api-server-timeout is not applying the user-defined timeout to the Kubeconfig created by Pykube because the monkey patching occurs after the Kubeconfig has been created.

## Changes

## Tests done

## TODO

- [x] I've assigned myself to this PR

2024-11-22 12:04 UTC, JTaeuber requested changes

2024-11-22 12:04 UTC, JTaeuber commented on kube_downscaler/scaler.py
In line 1146 
```python
api = helper.get_kube_api()
```
also gets called without an argument.

2024-11-22 12:27 UTC, samuel-esp commented on kube_downscaler/scaler.py
Eagle eyes 👀. Thank you for noticing that! I'll refactor it this afternoon

2024-11-25 11:42 UTC, JTaeuber approved these changes
LGTM

2024-11-27 14:32 UTC, merged