[helm chart] remplace name with fullname helper
caas-team/py-kube-downscaler pull request #77
Opened 2024-07-24 06:05 UTC by rekcah78

## Motivation

value nameOverride or fullnameOverride can't be use 

## Changes
**Helm Chart**
* replace name of ressources with the helper "fullname"
* add default labels for helm chart

## Tests done

* Deploying with and without full name replacement

## TODO

- [x] I've assigned myself to this PR

2024-08-12 12:28 UTC, JTaeuber requested changes

2024-08-12 12:28 UTC, JTaeuber commented on chart/templates/_helpers.tpl
The `py-kube-downscaler.name` helper will be obsolete with these changes, so it should be removed.

2024-08-12 12:28 UTC, JTaeuber commented on chart/templates/rbac.yaml
Please also change line 13 to `{{- $name := include "py-kube-downscaler.fullname" . }}`.

2024-08-12 12:30 UTC, JTaeuber commented
Other than that these changes are good. If you made the changes and rebased the branch so it includes the changes of https://github.com/caas-team/py-kube-downscaler/pull/78 we can merge this.

2024-08-12 17:05 UTC, rekcah78 commented on chart/templates/rbac.yaml
done

2024-08-12 17:08 UTC, rekcah78 commented on chart/templates/_helpers.tpl
done

2024-08-13 07:02 UTC, JTaeuber commented
Okay perfect, now we just need a rebase to resolve the current merge conflicts.

2024-09-03 13:29 UTC, JTaeuber approved these changes
LGTM

2024-09-03 13:29 UTC, merged